theme: jekyll-theme-minimal
title: Abi's Portfolio Home
description: This is still a work in progress, but I can't wait to show you what all I can do. This website was created to illustrate some of my skills in SQL, R, VBA, and other technical areas. Thank you for your interest in my wokr. Stay tuned for more!
Author: Abi Mooney
